package board

import "math/bits"

// GeneratePseudoLegalMoves appends every pseudo-legal move for the side to
// move into buf and returns the resulting slice. Pass a per-ply scratch buffer
// (e.g. stack[ply][:0]) to avoid allocating; passing nil also works.
//
// callers are responsible for verifying the legality of mvoes generated by this function
// this is to reduce redundant make/unmake move patterns
func (b *Board) GeneratePseudoLegalMoves(buf []Move) []Move {

	moves := buf[:0]

	occupancy := b.BlackOccupancy
	if b.WhiteToMove {
		occupancy = b.WhiteOccupancy
	}

	for bb := occupancy; bb != 0; bb &= bb - 1 {
		square := bits.TrailingZeros64(bb)
		b.generateMovesForPiece(b.MailBox[square], square, &moves)
	}

	return moves
}

// GenerateLegalMovesForPosition returns only fully legal moves. It is a
// convenience wrapper around GeneratePseudoLegalMoves for callers outside the
// hot search path (UCI move validation, perft roots, tests). It allocates.
func (b *Board) GenerateLegalMovesForPosition() []Move {

	pseudo := b.GeneratePseudoLegalMoves(make([]Move, 0, 64))

	// filter in place: the write index never passes the read index
	legal := pseudo[:0]

	for _, move := range pseudo {
		child := *b
		if err := child.MakeMove(move); err != nil {
			continue
		}
		if child.KingIsChecked(b.WhiteToMove) {
			continue
		}
		legal = append(legal, move)
	}

	return legal
}

func (b *Board) generateMovesForPiece(piece Piece, square int, moves *[]Move) {

	switch piece.Type() {
	case Pawn:
		b.generatePawnMoves(piece.IsWhite(), square, moves)
	case Rook:
		b.generateStraightMoves(piece.IsWhite(), square, moves)
	case Knight:
		b.generateKnightMoves(piece.IsWhite(), square, moves)
	case Bishop:
		b.generateDiagonalMoves(piece.IsWhite(), square, moves)
	case Queen:
		b.generateDiagonalMoves(piece.IsWhite(), square, moves)
		b.generateStraightMoves(piece.IsWhite(), square, moves)
	case King:
		b.generateKingMoves(piece.IsWhite(), square, moves)
	}
}

func (b *Board) generateDiagonalMoves(isWhite bool, startSq int, moves *[]Move) {

	friendly := b.BlackOccupancy
	if isWhite {
		friendly = b.WhiteOccupancy
	}

	addMovesFromMask(startSq, bishopAttacks(startSq, b.Occupancy)&^friendly, moves)
}

func (b *Board) generateStraightMoves(isWhite bool, startSq int, moves *[]Move) {

	friendly := b.BlackOccupancy
	if isWhite {
		friendly = b.WhiteOccupancy
	}

	addMovesFromMask(startSq, rookAttacks(startSq, b.Occupancy)&^friendly, moves)
}

func (b *Board) generateKnightMoves(isWhite bool, startSq int, moves *[]Move) {

	friendly := b.BlackOccupancy
	if isWhite {
		friendly = b.WhiteOccupancy
	}

	addMovesFromMask(startSq, knightAttacks[startSq]&^friendly, moves)
}

func (b *Board) generateKingMoves(isWhite bool, startSq int, moves *[]Move) {

	friendly := b.BlackOccupancy
	if isWhite {
		friendly = b.WhiteOccupancy
	}

	addMovesFromMask(startSq, kingAttacks[startSq]&^friendly, moves)

	// castling legality (not through/out of check, squares empty) cannot be
	// verified by the search's make-then-check, so it is fully enforced here
	if b.KingIsChecked(isWhite) {
		return // king can't castle if checked
	}

	home := blackHome
	canCastleKing := b.BlackCanCastleKingSide
	canCastleQueen := b.BlackCanCastleQueenSide
	if isWhite {
		home = whiteHome
		canCastleKing = b.WhiteCanCastleKingSide
		canCastleQueen = b.WhiteCanCastleQueenSide
	}

	if b.CanCastleKing(home, canCastleKing, isWhite) {
		*moves = append(*moves, NewMove(startSq, startSq+2, CastleFlag))
	}
	if b.CanCastleQueen(home, canCastleQueen, isWhite) {
		*moves = append(*moves, NewMove(startSq, startSq-2, CastleFlag))
	}
}

func (b *Board) generatePawnMoves(isWhite bool, startSq int, moves *[]Move) {

	enemyOccupancy := b.WhiteOccupancy
	index := blackIndex
	direction := -1
	startingRank := blackPawnStartingRank

	if isWhite {
		enemyOccupancy = b.BlackOccupancy
		index = whiteIndex
		direction = 1
		startingRank = whitePawnStartingRank
	}

	captureTargets := pawnAttacks[index][startSq] & enemyOccupancy

	for bb := captureTargets; bb != 0; bb &= bb - 1 {
		toSq := bits.TrailingZeros64(bb)
		b.addPawnMove(isWhite, NewMove(startSq, toSq, NoFlag), moves)
	}

	epTargets := pawnAttacks[index][startSq] & b.EnPassantTarget

	for bb := epTargets; bb != 0; bb &= bb - 1 {
		toSq := bits.TrailingZeros64(bb)
		*moves = append(*moves, NewMove(startSq, toSq, EnPassantCaptureFlag))
	}

	upOneSquare := startSq + (8 * direction)

	if !testBit(b.Occupancy, upOneSquare) {

		if didPromote := b.addPawnMove(
			isWhite,
			NewMove(startSq, upOneSquare, NoFlag),
			moves,
		); didPromote {
			// don't keep adding moves if a promotion exists
			return
		}

		if testBit(startingRank, startSq) {
			upTwoSquare := upOneSquare + (8 * direction)

			if !testBit(b.Occupancy, upTwoSquare) {
				*moves = append(*moves, NewMove(startSq, upTwoSquare, PawnTwoUpFlag))
			}
		}
	}
}

// addPawnMove appends the move, expanding it into the four promotion moves if
// the target square is on the promotion rank. Returns whether it promoted.
func (b *Board) addPawnMove(isWhite bool, move Move, moves *[]Move) bool {

	promotionRank := blackPawnPromotionRank
	if isWhite {
		promotionRank = whitePawnPromotionRank
	}

	if testBit(promotionRank, move.TargetSquare()) {
		for flag := PromoteToRookFlag; flag <= PromoteToQueenFlag; flag++ {
			*moves = append(*moves, NewMove(move.StartSquare(), move.TargetSquare(), flag))
		}
		return true
	}

	*moves = append(*moves, move)
	return false
}

func addMovesFromMask(startSq int, attackMask uint64, moves *[]Move) {
	for bb := attackMask; bb != 0; bb &= bb - 1 {
		*moves = append(*moves, NewMove(startSq, bits.TrailingZeros64(bb), NoFlag))
	}
}
